export const en = {
  "header.link_servers": "servers",
  "header.link_factions": "fractions",
  "header.link_player_rating": "player ratings",
  "header.link_monitoring": "monitoring",
  "header.link_wiki": "wiki",
  "header.link_news": "news",
  "header.link_shop": "shop",
  "header.personal_account_button_text": "Personal account",
  "header.mobile_menu_sign_in_button_text": "sign in",
  // Home page
  "home.page_name": "home",
  // Intro
  "lending.intro_top_title": "THE PLACE WHERE",
  "lending.intro_bottom_title": "everything is possible",
  "lending.intro_subtitle": "YOUR STORY, YOUR CHOICE, YOUR GAME",
  "lending.intro_button_text": "start game",
  "lending.intro_players_online": "THEY'RE PLAYING NOW",
  // News
  "lending.news_title": "LATEST NEWS",
  "lending.news_subtitle": "FOLLOW THE LATEST NEWS OF THE 1WRP WORLD",
  "lending.news_more_news_button_text": "MORE NEWS",
  // New in store
  "lending.new_in_store_title": "NEW ITEMS IN THE STORE",
  "lending.new_in_store_subtitle": "Visit the store to<br>see new items",
  "lending.new_in_store_button_text": "Open a store",
  // About
  "lending.about_title": "it",
  "lending.about_description": "1WRP it is a virtual universe with diverse roles similar to real life. You can become anyone you want by creating your own story in this world together with other players",
  // Servers
  "lending.servers_title": "SERVERS 1WRP",
  "lending.servers_server_name": "SERVER",
  "lending.servers_server_players_online": "online players",
  "lending.servers_server_players_registered": "registered",
  // Start play
  "lending.start_play_title": "HOW TO START PLAYING",
  "lending.step_one_title": "step 1",
  "lending.step_one_subtitle": "BUY AND INSTALL LICENSED GTA 5",
  "lending.step_one_description": "Licensed GTA 5 can be purchased on Steam, Epic Games or other digital distribution sites.",
  "lending.step_two_title": "step 2",
  "lending.step_two_subtitle": "INSTALL 1WRP MULTIPLAYER",
  "lending.step_two_description": "Download the official 1 WRP launcher. After the download is complete, install the launcher in a place that does not include the game files and without using Cyrillic characters in the path.",
  "lending.step_two_dwnload_launcher_button_texy": "DOWNLOAD THE LAUNCHER",
  "lending.step_three_title": "step 3",
  "lending.step_three_subtitle": "LAUNCH THE LAUNCHER AND CONNECT",
  "lending.step_three_description": "Launch the launcher and enter the IP address of the selected server in the window that opens.",
  "lending.step_two_select_server_button_texy": "SELECT A SERVER",
  // Character
  "lending.character_title_first_word": "LIVE",
  "lending.character_title_other_words": "A UNIQUE LIFE",
  "lending.character_subtitle": "IN THE WORLD",
  "lending.character_government_agencies_title": "Government agencies",
  "lending.character_government_agencies_info": "Government",
  "lending.character_info_more-title": "Federal Investigation Bureau",
  "lending.character_info_more-description": "Federal Investigation Bureau (FIB) - A government law enforcement organization dealing with serious and especially serious crimes, as well as internal and external intelligence. In the territory of the state, he is engaged in financial crimes, crimes related to government employees.",
  "lending.character_info_more-detailed_button_text": "more detailed",
  // Faqs
  "lending.faq_title": "DO YOU HAVE ANY QUESTIONS OR PROBLEMS?",
  "lending.faq_description": "If you could not find an answer to your question from the list, then you can contact our support service. We always try to improve our project in order to give you as many emotions as possible.",
  "lending.faq_button_texy": "SUPPORT CHAT",
  "lending.faq_question_title": "I have an important question. Is the answer here?",
  "lending.faq_question_description": "A family of bellows-type boxed musical instruments, also referred to as concert hand harmonics. This family includes accordion, concertina, accordion, bandoneon.",
  // Contacts
  "lending.contacts_title": "contacts",
  // Footer
  "footer.link_privacy_policy": "Privacy Policy",
  "footer.link_user_agreement": "User agreement",
  "footer.link_public_offer": "Public offer",
  "footer.link_cookie_policy": "Cookie Policy",
  "footer.link_server_rules": "Server Rules",
  "footer.support_channel": "Discord Support Channel VK Support",
  "footer.info": "Odin Game Development LLC INN 9703149875 OGRN 1237700457862 26, Vyronos Street. 3105. Limassol. LB. CY120009.",
  // Auth form
  "lending.auth_form_personal_account_title": "personal account",
  "lending.auth_form_login_field_placeholder": "Your password",
  "lending.auth_form_checkbox_remember_me_label": "Remember me",
  "lending.auth_form_forgot_password_text": "I forgot my password",
  "lending.auth_form_submit_form_button_text": "enter",
  "lending.auth_form_registration_button_text": "register",
  "lending.auth_via_social_media_networks_title": "VIA SOCIAL NETWORKS",
  "lending.auth_field_helper_text": "The field is required",
  // News page
  "news_list.page_name": "news",
  "news_list.title": "LATEST NEWS",
  "news_list.filter_tag_all": "all",
  "news_list.filter_tag_important": "important",
  "news_list.filter_tag_updates": "updates",
  "news_item.learn_more_button_text": "To learn more",
  "news.share_text": "To share",
  // Copy button
  "copy_button.auth_form_tooltip_text": "Some text",
  "copy_button.home_character_info_tooltip_text": "Copy the link to the profession",
  "copy_button.news_list_shared_tooltip_text": "Some text",
  // Remove start
  "news_item.updating_faction_system_title": "Updating the faction system",
  "news_item.updating_faction_system_subtitle": "Обновление системы фракций",
  "news_item.usual_news_title": "The usual news",
  "news_item.usual_news_subtitle": "To see new features",
  "news_item.date": "March 4",
  "news.description_top": "Original text Investigation Bureau (FIB) - a government law enforcement organization dealing with serious and especially serious crimes, as well as internal and external intelligence. In the territory of the state, he is engaged in financial crimes, crimes related to government employees.",
  "news.description_middle": "On the other hand, the current structure of the organization requires the definition and clarification of new proposals. Diverse and rich experience the existing structure of the organization is an interesting experiment to test the personnel training system, meets the urgent needs. Everyday practice shows that the further development of various forms of activity requires the definition and refinement of a personnel training system that meets urgent needs. The task of the organization, especially the new model of organizational activity, requires the definition and clarification of further directions of development. The significance of these problems is so obvious that the constant information and propaganda support of our activities requires us to analyze the directions of progressive development.",
  "news.description_bottom": "Small text (FIB) - A government law enforcement organization dealing with serious and especially serious crimes, as well as internal and external intelligence. He is engaged in financial crimes and crimes related to government employees on the territory of the state.",
  "news.list_item_1": "A menu item for real",
  "news.list_item_2": "Menu item",
  "news.list_item_3": "There's something else here",
  // Remove end
};
