export const ru = {
  "header.link_servers": "серверы",
  "header.link_factions": "фракции",
  "header.link_player_rating": "рейтинг игроков",
  "header.link_monitoring": "мониторинг",
  "header.link_wiki": "wiki",
  "header.link_news": "новости",
  "header.link_shop": "магазин",
  "header.personal_account_button_text": "Личный кабинет",
  "header.mobile_menu_sign_in_button_text": "Войти",
  // Home page
  "home.page_name": "главная",
  // Intro
  "lending.intro_top_title": "МЕСТО, ГДЕ",
  "lending.intro_bottom_title": "ВСЕ ВОЗМОЖНО",
  "lending.intro_subtitle": "ВАША ИСТОРИЯ, ВАШ ВЫБОР, ВАША ИГРА",
  "lending.intro_button_text": "НАЧАТЬ ИГРУ",
  "lending.intro_players_online": "СЕЙЧАС ИГРАЮТ",
  // News
  "lending.news_title": "ПОСЛЕДНИЕ НОВОСТИ",
  "lending.news_subtitle": "СЛЕДИТЕ ЗА ПОСЛЕДНИМИ НОВОСТЯМИ МИРА 1WRP",
  "lending.news_more_news_button_text": "БОЛЬШЕ НОВОСТЕЙ",
  // New in store
  "lending.new_in_store_title": "НОВИНКИ В МАГАЗИНЕ",
  "lending.new_in_store_subtitle": "Заходите в магазин что бы увидеть новые предметы",
  "lending.new_in_store_button_text": "Открыть магазин",
  // About
  "lending.about_title": "ЭТО",
  "lending.about_description": "1WRP это виртуальная вселенная с разнообразными ролями, аналогичными реальной жизни. Вы можете стать кем угодно, создавая свою историю в этом мире вместе с другими игроками",
  // Servers
  "lending.servers_title": "СЕРВЕРА 1WRP",
  "lending.servers_server_name": "СЕРВЕР",
  "lending.servers_server_players_online": "онлайн игроков",
  "lending.servers_server_players_registered": "зарегистрировано",
  // Start play
  "lending.start_play_title": "КАК НАЧАТЬ ИГРАТЬ В",
  "lending.step_one_title": "ШАГ 1",
  "lending.step_one_subtitle": "КУПИТЕ И УСТАНОВИТЕ ЛИЦЕНЗИОННУЮ GTA 5",
  "lending.step_one_description": "Лицензионную GTA 5 можно купить в Steam, Epic Games или на других площадках цифровой дистрибуции.",
  "lending.step_two_title": "ШАГ 2",
  "lending.step_two_subtitle": "УСТАНОВИТЕ 1WRP MULTIPLAYER",
  "lending.step_two_description": "Загрузите официальный лаунчер 1WRP. По окончании загрузки произведите установку лаунчера в место, не включающее файлы игры и без использования кириллических символов в пути.",
  "lending.step_two_dwnload_launcher_button_texy": "СКАЧАТЬ ЛАУНЧЕР",
  "lending.step_three_title": "ШАГ 3",
  "lending.step_three_subtitle": "ЗАПУСТИТЕ ЛАУНЧЕР И ПОДКЛЮЧАЙТЕСЬ",
  "lending.step_three_description": "Запустите лаунчер и в открывшемся окне введите IP адрес выбранного сервера.",
  "lending.step_two_select_server_button_texy": "ВЫБРАТЬ СЕРВЕР",
  // Character
  "lending.character_title_first_word": "ЖИВИ",
  "lending.character_title_other_words": "УНИКАЛЬНУЮ ЖИЗНЬ",
  "lending.character_subtitle": "В МИРЕ",
  "lending.character_government_agencies_title": "Государственные структуры",
  "lending.character_government_agencies_info": "Правительство",
  "lending.character_info_more-title": "Federal Investigation Bureau",
  "lending.character_info_more-description": "Federal Investigation Bureau (FIB) - правительственная правоохранительная организация занимающаяся тяжкими и особо тяжкими преступлениями, а так же внутренней и внешней разведкой. На территории штата занимается, финансовыми преступлениями, преступлениями связанными с государственными служащими.",
  "lending.character_info_more-detailed_button_text": "подробнее",
  // Faqs
  "lending.faq_title": "ПОЯВИЛИСЬ ВОПРОСЫ ИЛИ ВОЗНИКЛИ ПРОБЛЕМЫ?",
  "lending.faq_description": "Если вы не смогли найти ответ на свой вопрос из списка, то можете обратиться в нашу службу поддержки. Мы стараемся всегда улучшать нам проект что бы подарить вам как можно больше эмоций.",
  "lending.faq_button_texy": "ЧАТ ПОДДЕРЖКИ",
  "lending.faq_question_title": "У меня возник важный вопрос. Ответ тут?",
  "lending.faq_question_description": "Семейство коробчатых музыкальных инструментов сильфонного типа, также именуемые как концертные ручные гармоники. К этому семейству относятся баян, концертина, гармонь, бандонеон.",
  // Contacts
  "lending.contacts_title": "КОНТАКТЫ",
  // Footer
  "footer.link_privacy_policy": "Политика конфиденциальностиers",
  "footer.link_user_agreement": "Пользовательское соглашение",
  "footer.link_public_offer": "Публичная оферта",
  "footer.link_cookie_policy": "Политика Cookie файлов",
  "footer.link_server_rules": "Правила сервера",
  "footer.support_channel": "Канал поддержки в Discord Поддержка в ВК",
  "footer.info": "ООО “Один Гейм Девелопмент” ИНН 9703149875 ОГРН 1237700457862 26, Vyronos Street. 3105. Limassol. LB. CY120009.",
  // Auth form
  "lending.auth_form_personal_account_title": "ЛИЧНЫЙ КАБИНЕТ",
  "lending.auth_form_login_field_placeholder": "Ваш пароль",
  "lending.auth_form_checkbox_remember_me_label": "запомнить меня",
  "lending.auth_form_forgot_password_text": "забыл пароль",
  "lending.auth_form_submit_form_button_text": "войти",
  "lending.auth_form_registration_button_text": "зарегистрироваться",
  "lending.auth_via_social_media_networks_title": "ЧЕРЕЗ социальные сети",
  "lending.auth_field_helper_text": "Поле обязательно",
  // News page
  "news_list.page_name": "новости",
  "news_list.title": "ПОСЛЕДНИЕ НОВОСТИ",
  "news_list.filter_tag_all": "все",
  "news_list.filter_tag_important": "важные",
  "news_list.filter_tag_updates": "обновления",
  "news_item.learn_more_button_text": "Узнать больше",
  "news.share_text": "Поделиться",
  // Copy button
  "copy_button.auth_form_tooltip_text": "Какой-то текст",
  "copy_button.home_character_info_tooltip_text": "Скопировать ссылку на профессию",
  "copy_button.news_list_shared_tooltip_text": "Какой-то текст",
  // Remove start
  "news_item.updating_faction_system_title": "Обновление системы фракций",
  "news_item.updating_faction_system_subtitle": "Обновление системы фракций",
  "news_item.usual_news_title": "Обычная новость",
  "news_item.usual_news_subtitle": "Что бы увидеть новые возможности",
  "news_item.date": "4 марта",
  "news.description_top": "Original text Investigation Bureau (FIB) - правительственная правоохранительная организация занимающаяся тяжкими и особо тяжкими преступлениями, а так же внутренней и внешней разведкой. На территории штата занимается, финансовыми преступлениями, преступлениями связанными с государственными служащими.",
  "news.description_middle": "С другой стороны сложившаяся структура организации требуют определения и уточнения новых предложений. Разнообразный и богатый опыт сложившаяся структура организации представляет собой интересный эксперимент проверки системы обучения кадров, соответствует насущным потребностям. Повседневная практика показывает, что дальнейшее развитие различных форм деятельности требуют определения и уточнения системы обучения кадров, соответствует насущным потребностям. Задача организации, в особенности же новая модель организационной деятельности требуют определения и уточнения дальнейших направлений развития. Значимость этих проблем настолько очевидна, что постоянное информационно-пропагандистское обеспечение нашей деятельности требуют от нас анализа направлений прогрессивного развития.",
  "news.description_bottom": "Small text (FIB) - правительственная правоохранительная организация занимающаяся тяжкими и особо тяжкими преступлениями, а так же внутренней и внешней разведкой. На территории штата занимается, финансовыми преступлениями, преступлениями связанными с государственными служащими.",
  "news.list_item_1": "Пункт меню для настоящих",
  "news.list_item_2": "Пункт меню",
  "news.list_item_3": "Что-то здесь еще",
  // Remove end
};